name: Daily Reminder

on:
  schedule:
    - cron: "55 10 * * 1-5"
  workflow_dispatch:

jobs:
  notifification:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_URL }}
          content: "Remember to do daily report on excel sheet https://docs.google.com/spreadsheets/d/1tOiTJzIrldLkWuHsx9frZDtF_B_NxqBqTXf8WscaDcc/edit#gid=752255795
"
